### PR TITLE
Implemented a display of the difference between the update date and the current date.

### PR DESCRIPTION
**Pull request by ghost**
SSIA

### CODE REVIEW

**Comment by mattn** [comment]
I prefer to use https://github.com/BenJetson/humantime . humantime can display `hours ago` or `just now`.

**Comment by ghost** [comment]
Thanks！
 certainly, It seems better to replace to it.

**Comment by hashue** [comment]
I'll replace to it

**Comment by ghost** [comment]
@sheepla @mattn 
I tried humantime.
My opinion is shouldn't use it.
- I figure difficult to see layout of it for Japanese.
    e.g. `a day ago`,`about a month ago`
- It take more width compare to my implementation.

That's why I figure shouldn't use it.
What do you think?

FYI : demo of use humantime
image

**Comment by sheepla** [comment]
I was wondering whether to use the library or implement it with us. However the implementation of PR was easier to see and I liked it. So I will merge it. Thank you! ✨

**Pull request merged**
